if(EXISTS "/home/cosmos/alphazero-multi-game/build_with_torch/tests/core_tests[1]_tests.cmake")
  include("/home/cosmos/alphazero-multi-game/build_with_torch/tests/core_tests[1]_tests.cmake")
else()
  add_test(core_tests_NOT_BUILT core_tests_NOT_BUILT)
endif()
