if(EXISTS "/home/cosmos/alphazero-multi-game/build_with_torch/tests/game_tests[1]_tests.cmake")
  include("/home/cosmos/alphazero-multi-game/build_with_torch/tests/game_tests[1]_tests.cmake")
else()
  add_test(game_tests_NOT_BUILT game_tests_NOT_BUILT)
endif()
