if(EXISTS "/home/cosmos/alphazero-multi-game/build_with_torch/tests/integration_tests[1]_tests.cmake")
  include("/home/cosmos/alphazero-multi-game/build_with_torch/tests/integration_tests[1]_tests.cmake")
else()
  add_test(integration_tests_NOT_BUILT integration_tests_NOT_BUILT)
endif()
